### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by l89669** [aolko/Kettle#6]

**Comment by aolko** [comment]
Build artifacts are not avaliable currently, stay tuned

**Comment by l89669** [comment]
Nevermind. I've found a mirror repo for prok.pw. Now I can try setup the dev environment.

**Comment by aolko** [comment]
i'm using
```
maven {
            name = 'prok'
            url = 'https://nexus.aur.rocks/service/siesta/repository/browse/kk-central/'
        }
```
please check java branch, it's a current one

**Comment by l89669** [comment]
Thanks for your help.

**Comment by grand-trizmo** [comment]
still isnt buildable not sure why this was closed

**Comment by CDAGaming** [comment]
This shouldv'e been renamed to reflect the actual issue, which was the prok repository not functioning. This is still very WIP too...
